# Generated by Django 4.0.3 on 2022-03-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=70)),
                ('assignment', models.FileField(upload_to='pdfs/')),
                ('date', models.DateField()),
            ],
        ),
    ]
